title: ""
author: Pierre Navaro
email: navaro@math.cnrs.fr
logo: images/logo.png
only_build_toc_files: true

repository:
  url: https://github.com/pnavaro/NouvellesJulia
  branch: master  

html:
  home_page_in_navbar: true
  use_issues_button: false
  use_edit_page_button: true
  use_repository_button: true

sphinx:
    config:
        language: "fr"
        html_show_copyright: false
        html_last_updated_fmt: "%d %b %Y"
